language: python
jobs:
  include:
    - os: linux
      python: 3.5
      env:
        - BADGE=linux
    - os: linux
      python: 3.6
      env:
        - BADGE=linux
    - os: linux
      python: 3.7.6
      env:
        - BADGE=linux
    - os: linux
      python: 3.8
      env:
        - BADGE=linux
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: 
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - BADGE=windows
  allow_failures:
    - os: windows
  fast_finish: true

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - python setup.py install
script:
  - flake8 --exclude __init__.py --max-line-length=82 pyps4_2ndscreen
  - flake8 --ignore=E501 tests
  - pylint pyps4_2ndscreen
  - py.test --cov-report=xml --cov=pyps4_2ndscreen tests/
branches:
  only:
  - master
  - dev
after_success:
  - codecov