language: python
python:
  - "3.5"
  - "3.6"
  - "3.7.6"
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - python setup.py install
script:
  - flake8 --exclude __init__.py pyps4_2ndscreen
  - flake8 --ignore=E501 tests
  - pylint pyps4_2ndscreen
  - py.test --cov-report=xml --cov=pyps4_2ndscreen tests/
branches:
  only:
  - master
  - dev
after_success:
  - codecov